# Generated by Django 2.2 on 2019-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biao', '0002_auto_20190421_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='coleta',
            field=models.DateField(blank=True, null=True),
        ),
    ]
