# Generated by Django 2.2 on 2019-04-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biao', '0003_auto_20190421_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultura',
            name='coleta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultura',
            name='data',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
